### ISSUE TITLE
En tant qu'utilisateur, je veux avoir accès à un contenu visuellement qualitatif et fonctionnel

### ISSUE THREAD

**Issue by mharribey** [bastienrobert/la-ferme#35]
**Description**
Ajout de components dans l'UI Kit :
- [x] Button
- [x] Typo
- [x] Icons

Ajout de components dans l'app :
- [ ] Walkthrough
- [ ] Round
- [ ] Call ( or Pickup? )
- [ ] Slider
- [ ] Timeline + Avatar

**Figma**
00_Elements_UI

**Screenshot**
![00_Elements_UI](https://user-images.githubusercontent.com/22396630/78557415-0a408880-7811-11ea-847a-38ab23ab95d4.png)

**Comment by bastienrobert** [comment]
J'aurais plutôt eu tendance à mettre la Timeline, le PickUp et le Walkthrough (le truc que t'as appelé Slider) dans l'app directement. 
Peu de chances qu'on les utilise sur la landing page (cf. @solenerobichon @Celine-LP)

**Comment by mharribey** [comment]
Du coup j'ai pas compris je pense, pour moi l'UI Kit c'est tous les components d'UI qui vont être utilisés à plusieurs reprises dans l'app, donc pour moi tout ça, ça va dans l'app, tu peux m'éclairer ?

**Comment by bastienrobert** [comment]
En gros les composants dans l'UI kit c'est vraiment les principaux. Tout ce qui est bouton, typo, avatars, ce genre de choses. Dans l'atomic design c'est des "atoms". Le reste, par exemple la timeline, c'est une "molécule", elle s'assemble à partir de plusieurs atoms.

Les éléments de l'UI kit sont hyper lourd à dev vu qu'il faut les rendre compatible avec React-DOM et React Native. Du coup pour limiter la charge de développement la dessus, on essaye de mettre le moins de composants possible là dedans. Il faut mettre uniquement ceux qui seront utilisés côté app mobile et côté landing page.

Donc par exemple, le bouton décrocher on va jamais en avoir besoin sur la landing. Pas besoin de le rendre compatible avec React-DOM donc pas besoin qu'il soit dans l'UI kit. Il sera direct dans un dossier composant dans le package mobile

**Comment by bastienrobert** [comment]
Walkthrough ref. #66
